### PR TITLE
Trackside fix

### PR DESCRIPTION
**Pull request by owentmfoo**
- Add line to print decoded messages to log
- revert 039277f
- Add endSession to HexReader

### CODE REVIEW

**Comment by owentmfoo** [comment]
@ner24 
We've added a line that prints the converted messages so we can see the converted values even if the influx bit is not working. 
Influx also didn't like the new json format made in 039277f so we've reverted that trackside as well, to be investigated more..

**Comment by ner24** [comment]
Is influx still ignoring our timestamps? @owentmfoo

**Comment by owentmfoo** [comment]
@ner24 unfortunately yes.
I haven't got time to look at it for more detail, but an RTC in the pi could be a workaround for the time being.

**Comment by ner24** [comment]
Just realised that the commit has reenabled influx and disabled excel @owentmfoo

**Comment by owentmfoo** [comment]
@ner24, leaving the settings the same as what will be on the pi is probably not a bad thing. It means they don't have to change anything when they pull and upload it to the pi. We could refactor this in the future to use config files instead so when you pull the local configs don't change.

**Pull request merged**
